{% set name = "xaitk-saliency" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xaitk_saliency-{{ version }}.tar.gz
  sha256: 8cb8f6a48873c51ef5d2f71f3cda2dbe8c02856fb1d1093ed03ea5c9c56a51eb

build:
  skip: true  # [py>=400 or py2k]
  entry_points:
    - sal-on-coco-dets = xaitk_saliency.utils.bin.sal_on_coco_dets:sal_on_coco_dets
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy <2.0,>=1.22
    - scikit-image >=0.18.1
    - scikit-learn >=1.5
    - smqtk-classifier >=0.17.0
    - smqtk-core >=0.18.0
    - smqtk-descriptors >=0.16.0
    - smqtk-detection >=0.19.0
    - scipy >=1.9
    - click >=8.0.3
  run_constrained:
    - notebook >=7.2.2
    - matplotlib >=3.4.1
    - papermill >=2.3.3
    - pytorch >=1.9.0
    - torchvision >=0.10.0
    - tqdm ==4.66.3
    - kwcoco >=0.2.18
    - pyyaml >=6.0.1
    - shapely >=2.0.2

test:
  imports:
    - xaitk_saliency
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/XAITK/xaitk-saliency
  summary: Visual saliency map generation interfaces and baseline implementations for explainable AI.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - eveenhuis
    - Purg
    - bjrichardwebster
    - barry-ravichandran
